import React from 'react';
import { Card } from '../../components/UI/Card';
import { Car, Home, Utensils, ShoppingBag } from 'lucide-react';

export const ImpactDrivers: React.FC = () => {
  const drivers = [
    { icon: <Car className="w-6 h-6 text-indigo-500" />, name: "Transportation", percent: "28%", desc: "Derived primarily from single-passenger gasoline burning vehicles and commercial aviation routing." },
    { icon: <Home className="w-6 h-6 text-amber-500" />, name: "Home Energy", percent: "20%", desc: "Driven by fossil-fueled power grids supporting domestic heating, high cooling usage, and unoptimized electronics." },
    { icon: <Utensils className="w-6 h-6 text-rose-500" />, name: "Food Ecosystems", percent: "22%", desc: "Mainly generated by resource-heavy livestock supply chains, global shipping, and methane from organic food waste." },
    { icon: <ShoppingBag className="w-6 h-6 text-emerald-500" />, name: "Consumer Goods & Waste", percent: "30%", desc: "Fueled by fast fashion production cycles, electronics manufacturing, and non-recycled waste streams." },
  ];

  return (
    <section className="py-16 bg-slate-100/50 dark:bg-slate-850/40 border-y border-slate-200 dark:border-slate-800" aria-labelledby="drivers-heading">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-2xl mx-auto mb-12">
          <h2 id="drivers-heading" className="text-3xl font-bold text-slate-900 dark:text-white tracking-tight">What Creates the Most Impact?</h2>
          <p className="mt-3 text-slate-600 dark:text-slate-400">Global averages underscore that personal choices directly influence four pillars of macroeconomic emission production.</p>
        </div>
        
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {drivers.map((driver, i) => (
            <Card key={i} className="flex flex-col justify-between border-slate-200/60 dark:border-slate-700/60">
              <div>
                <div className="flex justify-between items-center mb-4">
                  <div className="p-2 rounded-lg bg-slate-50 dark:bg-slate-900">{driver.icon}</div>
                  <span className="text-2xl font-black text-slate-900 dark:text-white">{driver.percent}</span>
                </div>
                <h3 className="font-bold text-lg text-slate-900 dark:text-white mb-2">{driver.name}</h3>
                <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">{driver.desc}</p>
              </div>
            </Card>
          ))}
        </div>
      </div>
    </section>
  );
};